version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: catalogo
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5431:5432'
    volumes:
      - catalogo-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - catalogo-redis:/var/lib/redis/data

  catalogo:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app/:cached
      - bundle:/usr/local/bundle
      - rails_cache:/usr/src/app/tmp/cache
      - node_modules:/usr/src/app/node_modules
      - packs:/usr/src/app/public/packs
    links:
      - postgres
      - redis
    ports:
      - '3000:3000'
    env_file:
      - .env

volumes:
  catalogo-postgres:
  catalogo-redis:
  bundle:
  db_data:
  node_modules:
  rails_cache:
  packs:
